function partidostrain = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  PARTIDOSTRAIN = IMPORTFILE(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the data
%  as a table.
%
%  PARTIDOSTRAIN = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  PARTIDOSTRAIN = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  partidostrain = importfile("C:\Users\jorge\Desktop\prediccion\partidos_train.xlsx", "Hoja1", [2, 25]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-May-2021 12:04:41

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 25];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":C" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Equipo1", "Equipo2", "Resultado"];
opts.VariableTypes = ["string", "string", "double"];

% Specify variable properties
opts = setvaropts(opts, "Equipo1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Equipo1", "Equipo2"], "EmptyFieldRule", "auto");

% Import the data
partidostrain = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":C" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    partidostrain = [partidostrain; tb]; %#ok<AGROW>
end

end